import os
import requests
import datetime

# Setup environment variables
NOTION_TOKEN = os.environ['NOTION_API_KEY']
DATABASE_ID = os.environ['NOTION_DATABASE_ID']

headers = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28"
}

def process_unsynced_posts():
    # 1. Query for: Status="Published" AND Synced=False
    url = f"https://api.notion.com/v1/databases/{DATABASE_ID}/query"
    query_payload = {
        "filter": {
            "and": [
                {"property": "Status", "select": {"equals": "Published"}},
                {"property": "Synced", "checkbox": {"equals": False}}
            ]
        }
    }
    
    res = requests.post(url, json=query_payload, headers=headers)
    pages = res.json().get("results", [])

    if not pages:
        print("No new posts to sync.")
        return

    for page in pages:
        page_id = page["id"]
        props = page["properties"]
        
        # Extract metadata
        slug = props["slug"]["rich_text"][0]["plain_text"]
        notion_date = props["Date"]["date"]["start"] # YYYY-MM-DD
        
        # File paths
        final_filename = f"{notion_date}-{slug}.md"
        temp_path = f"_posts/{slug}.md" 
        final_path = f"_posts/{final_filename}"

        # 2. Rename the file generated by the GitHub Action
        if os.path.exists(temp_path):
            os.rename(temp_path, final_path)
            print(f"Processed: {final_filename}")

            # 3. Handle Cover Image
            cover = page.get("cover")
            if cover:
                img_url = cover.get("file", {}).get("url") or cover.get("external", {}).get("url")
                img_name = f"{slug}-cover.jpg"
                os.makedirs("assets/images", exist_ok=True)
                
                img_data = requests.get(img_url).content
                with open(f"assets/images/{img_name}", 'wb') as f:
                    f.write(img_data)
                
                # Inject image path into Frontmatter
                with open(final_path, 'r+') as f:
                    content = f.read()
                    if "image:" not in content:
                        f.seek(0, 0)
                        f.write(f"---\nimage: /assets/images/{img_name}\n" + content)

            # 4. HANDSHAKE: Update Notion to set Synced = True
            update_url = f"https://api.notion.com/v1/pages/{page_id}"
            update_payload = {"properties": {"Synced": {"checkbox": True}}}
            requests.patch(update_url, json=update_payload, headers=headers)
            print(f"Successfully marked '{slug}' as Synced in Notion.")

if __name__ == "__main__":
    process_unsynced_posts()
